# -*- coding: utf-8 -*-
"""V3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nNshdT9AsUD-T9rINe3kpSdEw0OsvDsS
"""

import numpy as np
import matplotlib.pyplot as plt


# Load data from the CSV file
data = np.genfromtxt('earthquake_datav2.csv', delimiter=',', names=True, dtype=None, encoding='utf-8', invalid_raise=False)

# Extract relevant fields using cleaned names
latitude = data['Latitude']
longitude = data['Longitude']
depth = data['Depth']
magnitude = data['Magnitude']
date = data['Date']
depth_categories = np.where(depth < 70, 'Shallow',
                             np.where(depth < 300, 'Intermediate', 'Deep'))
# Histogram of Earthquake Depths
plt.figure(figsize=(10, 6))
plt.hist(depth, bins=30, color='orange', alpha=0.7)
plt.title('Histogram of Earthquake Depths')
plt.xlabel('Depth (km)')
plt.ylabel('Frequency')
plt.grid(True)
plt.show()

import numpy as np
import matplotlib.pyplot as plt

# Load data from the CSV file
data = np.genfromtxt('earthquake_datav2.csv', delimiter=',', names=True, dtype=None, encoding='utf-8', invalid_raise=False)
latitude = data['Latitude']
longitude = data['Longitude']
depth = data['Depth']
magnitude = data['Magnitude']
date = data['Date']

# *Scatter Plot with Depth Representation*
plt.figure(figsize=(10, 6))
plt.scatter(longitude, latitude, s=depth*2, c=magnitude, cmap='viridis', alpha=0.5, edgecolors='w')
plt.colorbar(label='Magnitude')
plt.title('Earthquake Locations Colored by Magnitude and Sized by Depth')
plt.xlabel('Longitude')
plt.ylabel('Latitude')
plt.grid(True)
plt.show()

import numpy as np
import matplotlib.pyplot as plt
import datetime

# Load data from the CSV file
data = np.genfromtxt('earthquake_datav2.csv', delimiter=',', names=True, dtype=None, encoding='utf-8', invalid_raise=False)
latitude = data['Latitude']
longitude = data['Longitude']
depth = data['Depth']
magnitude = data['Magnitude']
date = data['Date']
#Daily Earthquake Counts with Visualization
# Convert date strings to numpy datetime64 for easy manipulation
dates = np.array([np.datetime64(datetime.datetime.strptime(d, '%d-%m-%Y')) for d in date])
unique_days, counts = np.unique(dates.astype('datetime64[D]'), return_counts=True)

plt.figure(figsize=(12, 6))
plt.plot(unique_days, counts, marker='o', linestyle='-', color='blue')
plt.title('Number of Earthquakes Per Day')
plt.xlabel('Date')
plt.ylabel('Number of Earthquakes')
plt.xticks(rotation=45)
plt.grid(True)
plt.tight_layout()
plt.show()

import numpy as np
import matplotlib.pyplot as plt
import datetime

# Load data from the CSV file
data = np.genfromtxt('earthquake_datav2.csv', delimiter=',', names=True, dtype=None, encoding='utf-8', invalid_raise=False)
latitude = data['Latitude']
longitude = data['Longitude']
depth = data['Depth']
magnitude = data['Magnitude']
date = data['Date']
#Box Plot for Magnitude
plt.figure(figsize=(10, 6))
plt.boxplot(magnitude)
plt.title('Box Plot of Earthquake Magnitudes')
plt.xlabel('Magnitude')
plt.grid(True)
plt.show()

import numpy as np
import matplotlib.pyplot as plt
import datetime
# Load data from the CSV file
data = np.genfromtxt('earthquake_datav2.csv', delimiter=',', names=True, dtype=None, encoding='utf-8', invalid_raise=False)
latitude = data['Latitude']
longitude = data['Longitude']
depth = data['Depth']
magnitude = data['Magnitude']
date = data['Date']
#Correlation of Magnitude and Depth
plt.figure(figsize=(10, 6))
plt.scatter(depth, magnitude, alpha=0.5)
plt.title('Magnitude vs Depth')
plt.xlabel('Depth (km)')
plt.ylabel('Magnitude')
plt.grid(True)
plt.show()